### ISSUE TITLE
Ensure that google analytics are not present in German Advocacy campaign

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/petitions.mozilla.org#7]
Just checked the source, and GA is still there. We still want to remove for this campaign, yes?

@shaghdoosti

**Comment by shaghdoosti** [comment]
Yes please!

**Comment by ScottDowne** [comment]
Removed: https://github.com/mozilla/petitions.mozilla.org/commit/e9cb450222ff8612e5b318cba1e831336ee7aa61

**Comment by secretrobotron** [comment]
@ScottDowne @adamlofting can you make sure there's nothing in the landing page for opt-in as well?

**Comment by ScottDowne** [comment]
@secretrobotron I'm not following. Which landing page is this?

**Comment by adamlofting** [comment]
I'd like to understand the decision process behind this?

**Comment by secretrobotron** [comment]
@shaghdoosti @valianttry any words of wisdom? When we were first launching the campaign, GA was a real concern.

**Comment by shaghdoosti** [comment]
Hey - 

Yes, so talking to a few people I was told that the German community was particularly sensitive around things like Google Analytics. That combined with the fact that this is a campaign against data retention felt like it could potentially create a lot of backlash. Again because this is our first non english campaign I was trying to play it as safe as possible. 

Happy to hear feedback or any other points of view Adam.
